---
name: Test .NET application

on:
  workflow_call:
    inputs:
      runs_on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      
      dotnet_version:
        description: Version of dotnet to use
        type: string
        default: 5.0.x
        
      report_name: 
        description: Report name
        type: string
        default: "Tests report"
        
      test_path:
        description: The folder containing the project to build
        type: string
        default: .
jobs:
  Test:
    runs-on: ${{ inputs.runs_on }}
    defaults:
      run:
        working-directory: ${{ inputs.test_path }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
        
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: (success() || failure())
        with:
          name: ${{ inputs.report_name }}
          working-directory: ${{ inputs.test_path }}
          path: TestResults/test-results.trx
          reporter: dotnet-trx
          fail-on-error: true

