
name: Push .NET NuGet package

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        description: NuGet name.
        type: string
      
      dotnet-version:
        description: Version of dotnet to use
        type: string
        default: 5.0.x
      
      project-folder:
        description: The folder containing the project to build
        type: string
        default: .
      
jobs:
  build:
    name: Build .NET NuGet package.
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Build and Pack NuGet package
        run: dotnet pack -c Release
      - name: Upload NuGet package to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: ${{ project-name }}_NuGet_package
          path: ${{ inputs.project-folder }}/bin/Release/ 
  
  release:
    name: Push .NET NuGet package to Github packages.  
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download nuget package artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ project-name }}_NuGet_package
      - name: Prep packages
        run: dotnet nuget add source --username danila032040 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Red-Papers-Studio/index.json"
      - name: Push package to GitHub packages
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"    
      
