---
name: Test .NET application

on:
  workflow_call:
    inputs:
      runs_on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      
      dotnet_version:
        description: Version of dotnet to use
        type: string
        default: 5.0.x
        
      project_name:
        description: Project name
        type: string
        default: "Project"
        
      test_path:
        description: The folder containing the project to build
        type: string
        default: .
jobs:
  test:
    name: Test .NET app
    runs-on: ${{ inputs.runs_on }}
    defaults:
      run:
        working-directory: ${{ inputs.test_path }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test  --no-build 
                          --verbosity normal 
                          --collect:"XPlat Code Coverage" 
                          --logger "trx;LogFileName=test-results.trx" 
                          --results-directory "TestResults"
        
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: (success() || failure())
        with:
          name: Test results for ${{ inputs.project_name }}
          working-directory: ${{ inputs.test_path }}
          path: TestResults/test-results.trx
          reporter: dotnet-trx
          fail-on-error: true

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{ inputs.test_path}}/TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'
          
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          hide_and_recreate: true
          path: code-coverage-results.md
          header: Code Coverage results for ${{ inputs.project_name }}

