---
name: Build .NET application

on:
  workflow_call:
    inputs:
      runs_on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      
      dotnet_version:
        description: Version of dotnet to use
        type: string
        default: 5.0.x
      
      project_path:
        description: The folder containing the project to build
        type: string
        default: .
            
      publish_configuration:
        description: Configuration to publish
        type: string
        default: Release
      
      artifact_name:
        description: Name of the artifact to upload
        type: string
        default: Published Application
        
      prepare_rps_packages:
        type: boolean
        default: true

jobs:
  build:
    name: Build .NET app
    
    runs-on: ${{ inputs.runs_on }}
    defaults:
      run:
        working-directory: ${{ inputs.project_path }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          
      - name: Prepare RPS packages
        if: ${{ inputs.prepare_rps_packages }}
        run: dotnet nuget add source --username danila032040 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Red-Papers-Studio/index.json"
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Publish
        run: dotnet publish -c ${{ inputs.publish_configuration }} -o publish
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.project_folder }}/publish/**
          if-no-files-found: error

